name: flutter_shazam_kit_example
description: Demonstrates how to use the flutter_shazam_kit plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_shazam_kit:
    path: ../
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true