name: flutter_shazam_kit
description: A plugin that helps you detect songs through your device's microphone.
version: 1.0.2
homepage: https://github.com/ssttonn/flutter_shazam_kit

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sstonn.flutter_shazam_kit
        pluginClass: FlutterShazamKitPlugin
      ios:
        pluginClass: FlutterShazamKitPlugin
