name: flutter_shazam_kit_platform_interface
description: A common platform interface for the flutter_shazam_kit plugin.
repository: https://github.com/ssttonn/flutter_shazam_kit/flutter_shazam_kit_platform_interface
version: 1.0.3+1
issue_tracker: https://github.com/ssttonn/flutter_shazam_kit/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
